name: Automatic Data Preprocessing

on:
  push:
    branches:
      - main

jobs:
  preprocessing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas scikit-learn

      - name: Run preprocessing script
        run: |
          python preprocessing/automate_Muhammad-Hafidh-Shovi.py

      - name: Commit preprocessing result
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add preprocessing/stunting_wasting_preprocessed.csv
          git commit -m "Update preprocessed dataset" || echo "No changes to commit"
          git push
